config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:index, :show]
  end
  
  root to: "movies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  searchkick

  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def search
    if params[:search].present?
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all
    end
  end

  def index
    @movies = Movie.all
  end

  def show
    @reviews = @movie.reviews.order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @movie = current_user.movies.build
  end

  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:image, :title, :description, :movie_length, :director, :rating, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie

  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = current_user.reviews.build
  end

  def edit
  end

  def create
    @review = current_user.reviews.build(review_params)
    @review.movie_id = @movie.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Movie Reviews", root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li= link_to "New Movie", new_movie_path, class: "active"
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign Up", new_user_registration_path, class: "active"
          %li= link_to "Sign In", new_user_session_path, class: "active"
      = form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do
        %p
          = text_field_tag :search, params[:search], class: "form-control"
          = submit_tag "Search", name: nil, class: "btn btn-default"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MoviewReview
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    =render 'layouts/header'
    .container
      %main
        -flash.each do |name, message|
          =content_tag(:div, message, class: "alert alert-info")
        = yield
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/movies/_form.html.haml
= form_for @movie, html: { multipart: true } do |f|
  - if @movie.errors.any?
    #error_explanation
      %h2= "#{pluralize(@movie.errors.count, "error")} prohibited this movie from being saved:"
      %ul
        - @movie.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title, { class: "form-control" } 
  .field
    = f.label :description
    = f.text_area :description, { class: "form-control" }
  .field
    = f.label :movie_length
    = f.text_field :movie_length, { class: "form-control" }
  .field
    = f.label :director
    = f.text_field :director, { class: "form-control" }
  .field
    = f.label :rating
    = f.text_field :rating, { class: "form-control" }

  .field
    = f.label :image
    = f.file_field :image, { class: "form-control" }
  .actions
    %br/
    %br/
    = f.submit 'Save', { class: "btn btn-default" }

app/views/movies/edit.html.haml
%h1 Editing movie

= render 'form'

= link_to 'Show', @movie
\|
= link_to 'Back', movies_path

app/views/movies/index.html.haml
- if !user_signed_in?
  .jumbotron
    %h1 Your Favorite Movies Reviewed
    %p Hashtag hoodie mumblecore selfies. Authentic keffiyeh leggings Kickstarter, narwhal jean shorts XOXO Vice Austin cardigan. Organic drinking vinegar freegan pickled.
    %p= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg"
.row
  - @movies.each do |movie|
    .col-sm-6.col-md-3
      .thumbnail=link_to (image_tag movie.image.url(:medium), class: 'image'), movie

app/views/movies/new.html.haml
%h1 New movie

= render 'form'

= link_to 'Back', movies_path

app/views/movies/search.html.haml
.row
  - @movies.each do |movie|
    .col-sm-6.col-md-3
      .thumbnail=link_to (image_tag movie.image.url(:medium), class: 'image'), movie

app/views/movies/show.html.haml
.panel.panel-default
  .panel-body
    .row
      .col-md-4
        =image_tag @movie.image.url(:medium)
        .star-rating{:"data-score"=>@avg_review}
        %em="#{@reviews.length} Reviews"
        .table-responsive
        %table.table
          %tbody
            %tr
              %td
                %b Title:
              %td=@movie.title
            %tr
              %td
                %b Description:
              %td=@movie.description
            %tr
              %td
                %b Movie length:
              %td=@movie.movie_length
            %tr
              %td
                %b Director:
              %td= @movie.director
            %tr
              %td
                %b Rating:
              %td=@movie.rating
        =link_to "Write a Review", new_movie_review_path(@movie)
      .col-md-7.col-md-offset-1
        %h1.review_title=@movie.title
        %p=@movie.description
        -if @reviews.blank?
          %h3 No reviews just yet, would you like to add the first one!
          =link_to "Write a Review", new_movie_review_path(@movie), class: "btn btn-warning"
        -else
          - @reviews.each do |review|
            .reviews
              .star-rating{:"data-score"=>review.rating}
              %p.comment=review.comment
              %p.created_at Submitted #{time_ago_in_words(review.created_at)} Ago
= link_to 'Edit', edit_movie_path(@movie)
\|
= link_to 'Back', movies_path

app/views/reviews/_form.html.haml
= form_for([@movie, @review]) do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :rating
    #star-rating
  .field
    %br/
    = f.label :comment
    = f.text_area :comment, { class: "form-control" }
  .actions
    %br/
    = f.submit 'Save', class: "btn btn-default"

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Back', movie_path(@movie)

app/views/reviews/new.html.haml
%h1 New review

= render 'form'

= link_to 'Back', movie_path(@movie)